apiVersion: v1
kind: Service
metadata:
  name: service-comments
spec:
  selector:
    app: comments
  ports:
    - name: http
      protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: service-event-bus
spec:
  selector:
    app: event-bus
  ports:
    - name: http
      protocol: TCP
      port: 4005
      targetPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: service-moderation
spec:
  selector:
    app: moderation
  ports:
    - name: http
      protocol: TCP
      port: 4003
      targetPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: service-post
spec:
  selector:
    app: posts
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: service-query
spec:
  selector:
    app: query
  ports:
    - name: http
      protocol: TCP
      port: 4002
      targetPort: 4002
---

apiVersion: v1
kind: Service
metadata:
  name: service-client
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000      
