apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
spec:
  containers:
    - name: mon-conteneur-client
      image: client:client
      ports:
        - containerPort: 3000

